const Strings = {
  dashboard: 'Dashboard',
  assets: 'Assets',
  welcomeWithComa: 'Welcome,',
  portfolioOverview: 'Portfolio Overview',
  recentActivity: 'Recent Activity',
  assetAllocation: 'Asset Allocation',
  historicalPerformance: 'Historical Performace',
  addAsset: 'Add Asset',
  name: 'Name',
  type: 'Type',
  quantity: 'Quantity',
  totalPrice: 'Total price',
  percentageChange: 'Percentage change',
  actions: 'Actions',
  purchaseDate: 'Purchase date',
  completeAllFields: 'Complete all fields',
  assetDeleteConfirmationMessage: 'Are you sure you want to delete this asset? This action cannot be undone.',
  areYouSure: 'Are you sure?',
  confirm: 'Confirm',
  cancel: 'Cancel',
  transaction: 'Transaction',
  portfolioValue: 'Portfolio Value',
  crypto: 'Crypto',
  stocks: 'Stocks',
  bond: 'Bond',
  type: 'Type',
  name: 'Name'
}

export default Strings;